baseURL: "https://mohamedfawas.github.io/"
languageCode: "en-us"
title: "Mohamed Fawas T"
theme: hugo-profile
# themesDir = "D:/mohamedfawas/mohamedfawas.github.io/themes"


Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Mohamed Fawas"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Mohamed Fawas."
    subtitle: "I work in data science and machine learning projects"
    content: "A passionate data science student from India"
    image: /fazdp.jpg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mohamedfawas
        - icon: fab fa-twitter
          url: https://twitter.com/MOHAMEDFAWAS182
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "trip.jpg"
    content: |-
      I am a final year data science student at IIITM-k. I am currently working as a Full time AI/ML intern at [Reflections Info Systems PVT LTD](https://reflectionsglobal.com/). 

      I am currently working on building my skills in computer vision projects.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "SQL"
        - "Open CV"
        # - "React"
        # - "Node"
        # - "Express"

  # Experience
  experience:
    enable: true
    items:
      - job: "Full time AI/ML intern"
        company: "Reflections Info Systems PVT LTD"
        companyUrl: "https://reflectionsglobal.com/"
        date: "Feb 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I am currently focusing on computer vision projects"

      - job: "Part time AI/ML intern"
        company: "Reflections Info Systems PVT LTD"
        companyUrl: "https://reflectionsglobal.com/"
        date: "Aug 2021 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://github.com/mohamedfawas/Bank-assistant-chatbot"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Worked with the chatbot development team and created a chatbot, using RASA framework, that can be used as bank assistant.

          - Chatbot development.
          - RASA.

      - job: "Project Intern"
        company: "TCS iON"
        companyUrl: "https://www.tcsion.com/"
        date: "Mar 2021 - Jun 2021"
        info:
          enable: true
        featuredLink:
          enable: true
          url: "https://github.com/mohamedfawas/RIO-125-Forecasting-System---Project-Demand-of-Products-at-a-Retail-Outlet-Based-on-Historical-Data"
        content: |
          Developed a forecasting system with the help of ARIMA models and facebook's prophet library. This forecasting system is used for predicting the demand for products at a retail outlet based on historical data.

          - Time Series Analysis
          - fbprophet.

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Science in Computer Science (specialization : Data Analytics)"
        school:
          name: "Indian Institute Of Information Technology and Management - Kerala"
          url: "https://example.org"
        date: "2020 - 2022"
        GPA: "7.7 out of 10.0"
        # content: |-
        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Statistics"
        school:
          name: "FAROOK COLLEGE - Kozhikode"
          url: "https://www.farookcollege.ac.in/"
        date: "2017 - 2020"
        GPA: "7.8 out of 10.0"
        content: |-
          Complementary Subjects:
          - Actuarial science
          - Mathematics

          Extracurricular Activities
            - Co-founder of 'Statistics Premier League' at Farook College (Autonomous ), Kozhikode. It's a championship program with a chain of games. This included the participation of students from the college.  
            
        featuredLink:
          enable: false 
          name: "My academic record"
          url: "https://example.com"
      - title: "Higher Secondary"
        school:
          name: "Malabar English School Kottakkal"
          url: "http://malabarenglishschool.com/"
        GPA: "95.32% "
        content: |-
          Graduated in Bio Science with full A+ in Higher secondary examinations.

        featuredLink:
          enable: false
          url: "https://example.com"

  # projects
  projects:
    enable: true
    items:
      # - title: Hugo Profile
      #   content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile.png
      #   featured:
      #     name: Demo
      #     link: https://hugo-profile.netlify.app
      #   # badges:
      #   #   - "Hugo"
      #   #   - "Bootstrap"
      #   #   - "Javascript"
      #   links:
      #     - icon: fa fa-envelope
      #       url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/hugo-profile
      #     - icon: fab fa-twitter
      #       url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      # - title: Image Converter
      #   content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   # badges:
      #   #   - "Django"
      #   #   - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   # badges:
      #   #   - "Hugo"
      #   #   - "Bootstrap"
      #   #   - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: fawastmh@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/mohamedfawas
      linkedin: https://www.linkedin.com/in/mohamed-fawas/
      twitter: https://twitter.com/MOHAMEDFAWAS182
      instagram: https://www.instagram.com/fawas_182
      # facebook: https://facebook.com
